### ISSUE TITLE
Error when disconnecting an old version of firmware

### ISSUE THREAD

**Issue by MauroMombelli** [cleanflight/cleanflight-configurator#466]
Hi,

i jus received a little emachine gx95, it uses a sp3evo but with an old version of firmware (or so say the configurator); then i disconnected to upload a newer firmware, but the main windows remain blank aside from the top and lateral menu.

log:
```
main.js:80 Libraries: jQuery - 2.1.4, d3 - 3.5.6, three.js - 72
port_handler.js:71 Selecting last used port: /dev/ttyACM0
serial_backend.js:49 Connecting to: /dev/ttyACM0
serial.js:132 SERIAL: Connection opened with ID: 2, Baud: 115200
serial.js:259 SERIAL: Connection with ID: 2 closed, Sent: 36 bytes, Received: 125 bytes
main.html#:1 Error in response to serial.send: TypeError: Cannot read property 'bytesSent' of undefined
    at Object.callback (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/serial.js:327:43)
    at send (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/serial.js:305:13)
    at Object.send (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/serial.js:358:13)
    at Object.TABS.cli.cleanup (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/tabs/cli.js:225:12)
    at GUI_control.tab_switch_cleanup (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/gui.js:247:31)
    at HTMLAnchorElement.<anonymous> (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/main.js:111:17)
    at HTMLAnchorElement.dispatch (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:6466)
    at HTMLAnchorElement.r.handle (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:3241)
    at Object.trigger (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:5574)
    at HTMLAnchorElement.<anonymous> (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:11542)
    at Function.each (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:2:2882)
    at n.fn.init.each (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:2:847)
    at n.fn.init.trigger (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:11518)
    at n.fn.init.n.fn.(anonymous function) [as click] (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:4:5101)
main.html#:1 Unchecked runtime.lastError while running serial.send: Serial connection not found.
    at send (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/serial.js:305:13)
    at Object.send (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/serial.js:358:13)
    at Object.TABS.cli.cleanup (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/tabs/cli.js:225:12)
    at GUI_control.tab_switch_cleanup (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/gui.js:247:31)
    at HTMLAnchorElement.<anonymous> (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/main.js:111:17)
    at HTMLAnchorElement.dispatch (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:6466)
    at HTMLAnchorElement.r.handle (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:3241)
    at Object.trigger (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:5574)
    at HTMLAnchorElement.<anonymous> (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:11542)
    at Function.each (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:2:2882)
    at n.fn.init.each (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:2:847)
    at n.fn.init.trigger (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:3:11518)
    at n.fn.init.n.fn.(anonymous function) [as click] (chrome-extension://enacoimjcgeinfnnnpajinjgmkahmfgb/js/libraries/jquery-2.1.4.min.js:4:5101)
port_handler.js:31 PortHandler - Removed: /dev/ttyACM0
port_handler.js:99 PortHandler - Found: /dev/ttyACM0
```

**Comment by hydra** [comment]
try latest version, should be fixed now.

**Comment by BadRaven** [comment]
I had this too TODAY on the same quad AND on another quad with the same FC. Had to install an old version of configurator to adjust PIDS which was all that was required.

**Comment by MauroMombelli** [comment]
Your issue seems different as this one the configurator is usable unless
you do a specific sequence of action. Can you get the error log from the js
console?  Maybe is better if youbopen a different issue and in case it will
be flag as duplicate.
